#!/bin/bash

set -euo pipefail

if ! groups | grep -qw admin; then
    echo >&2 "Error: must run phase1 as an admin user"
    exit 1
fi
scriptdir="$(cd "$(dirname "$0")" && pwd -P)"
PATH="$scriptdir:$scriptdir/scripts:$PATH"

unset HOMEBREW_AUTO_UPDATE

usage() {
    echo >&2 "${0##*/} [options]"
    echo >&2
    echo >&2 "Options:"
    echo >&2
    echo >&2 "  -x  Install Xcode rather than CLT"
    exit 2
}

xcode=0
while getopts xh opt; do
    case "$opt" in
        x)
            xcode=1
            ;;
        \? | h)
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

# Enable Firewall
sudo defaults write /Library/Preferences/com.apple.alf globalstate -bool true
sudo defaults write /Library/Preferences/com.apple.alf allowsignedenabled -bool false

# Enable Stealth Mode
sudo defaults write /Library/Preferences/com.apple.alf stealthenabled -bool true

# Disable Bonjour multicast advertisements:
sudo defaults write /Library/Preferences/com.apple.mDNSResponder.plist NoMulticastAdvertisements -bool YES

# Avoid captive portal hijacking attacks
sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.captive.control Active -bool false

# Don't show hostname at the login screen
sudo defaults write /Library/Preferences/com.apple.loginwindow AdminHostInfo ""

# Crank up the max open files, etc
sudo sh -c "echo kern.sysv.shmall=65536 >>/etc/sysctl.conf"
sudo sh -c "echo kern.sysv.shmmax=16777216 >>/etc/sysctl.conf"
sudo sh -c "echo kern.maxfiles=10485760 >>/etc/sysctl.conf"
sudo sh -c "echo kern.maxfilesperproc=1048576 >>/etc/sysctl.conf"
sudo sh -c "sort -u /etc/sysctl.conf >/tmp/foo && mv /tmp/foo /etc/sysctl.conf"
sudo sysctl -w $(cat /etc/sysctl.conf)

# Sane permissions for /opt
sudo mkdir -p /opt
sudo chmod g+wXs /opt
sudo chmod g+wX /opt
# sudo chgrp -R admin /opt

if ! xcode-select -p >/dev/null 2>&1; then
    if [ $xcode -eq 1 ]; then
        install-xcode
    else
        install-clt
    fi
fi

export HOMEBREW_PREFIX="/opt/homebrew"
PATH="$HOMEBREW_PREFIX/bin:$PATH"

# Install system homebrew
if [ ! -e $HOMEBREW_PREFIX/bin/brew ]; then
    sudo chgrp admin /opt
    sudo chmod g+ws /opt
    install-brew $HOMEBREW_PREFIX
fi

# Install zsh into system homebrew
# Work around checksum mismatch issue with 5.4.2 tarballs on sourceforge
sed -ibak -e 's#https://downloads.sourceforge.net/project/zsh/.*/5.4.2/#http://www.zsh.org/pub/#g' $HOMEBREW_PREFIX/Library/Taps/homebrew/homebrew-core/Formula/zsh.rb && rm -f $HOMEBREW_PREFIX/Library/Taps/homebrew/homebrew-core/Formula/zsh.rbbak
brew install zsh

# Add zsh to /etc/shells
# Add system homebrew bin & man dirs to appropriate paths.d
install-brew-system $HOMEBREW_PREFIX

# Install apps from casks
install-casks "$@"

# The bug ostiarius fixes in El Capitan was fixed by Apple in macOS Sierra
osx_version="$(sw_vers -productVersion)"
case "$osx_version" in
    10.11*)
        brew cask install ostiarius
        ;;
esac

# Extra installers
if [ -d $HOMEBREW_PREFIX/Caskroom/whatsyoursign ]; then
    open $HOMEBREW_PREFIX/Caskroom/whatsyoursign/*/WhatsYourSign\ Installer.app 2>/dev/null
fi

# Reload the Quick Look generators list
qlmanage -r
