#!/bin/sh

if [ $# -eq 0 ]; then
    set -- core
fi

export HOMEBREW_PREFIX=/Users/Shared/homebrew
PATH="$HOMEBREW_PREFIX/bin:$PATH"

scriptsdir="$(cd "$(dirname "$0")" && pwd -P)"
for group; do
    brew bundle --verbose "--file=$scriptsdir/Masfile-$group"
done
