#!/bin/sh

install-brew "${HOMEBREW_PREFIX:-/opt/homebrew}"

if [ ! -e /etc/paths.d/homebrew ]; then
    sudo sh -c "echo '$HOMEBREW_PATH/bin' >/etc/paths.d/homebrew"
fi
if [ ! -e /etc/manpaths.d/homebrew ]; then
    sudo sh -c "echo '$HOMEBREW_PATH/share/man' >/etc/manpaths.d/homebrew"
fi

if [ -e "$HOMEBREW_PATH/bin/zsh" ] && ! grep -q "$HOMEBREW_PATH/bin/zsh" /etc/shells; then
    sudo sh -c "echo '$HOMEBREW_PATH/bin/zsh' >>/etc/shells"
fi

