#!/bin/bash

set -euo pipefail

touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
trap 'rm -f /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress' EXIT INT TERM
PROD=$(softwareupdate -l |
       grep "\*.*Command Line" |
       awk -F"*" '{print $2}' | tail -n 1 |
       sed -e 's/^ *//' |
       tr -d '\n')
softwareupdate -i "$PROD" --verbose
