#!/bin/sh

HOMEBREW_PREFIX="${1:-${HOMEBREW_PREFIX:-$(brew --prefix 2>/dev/null || echo /opt/homebrew)}}"

install-brew -s "$HOMEBREW_PREFIX"

if [ ! -e /etc/paths.d/homebrew ]; then
    sudo sh -c "echo '$HOMEBREW_PREFIX/bin' >/etc/paths.d/homebrew"
fi
if [ ! -e /etc/manpaths.d/homebrew ]; then
    sudo sh -c "echo '$HOMEBREW_PREFIX/share/man' >/etc/manpaths.d/homebrew"
fi
