#!/bin/sh
# Personal preferences and configuration. The settings in
# setup-admin/setup-user are what I'd consider reasonable defaults for anyone
# rather than my personal preferences.

: ${HOMEBREW_PREFIX:=$(brew --prefix 2>/dev/null || echo /usr/local)}

# Dock on the left, autohide
defaults write com.apple.dock autohide 1
defaults write com.apple.dock orientation left
defaults write com.apple.dock tilesize 45

# Hide desktop icons completely
defaults write com.apple.finder CreateDesktop -bool false

# Disable Dashboard
defaults write com.apple.dashboard mcx-disabled -bool true

# Zsh is my preferred shell
if [ -e "$HOMEBREW_PREFIX/bin/zsh" ] && grep -qx "$HOMEBREW_PREFIX/bin/zsh" /etc/shells; then
    chsh -s "$HOMEBREW_PREFIX/bin/zsh"
fi
