#!/bin/bash

set -euo pipefail

scriptdir="$(cd "$(dirname "$0")" && pwd -P)"
PATH="$scriptdir:$PATH"

usage () {
    echo >&2 "${0##*/} [options]"
    echo >&2
    echo >&2 "Options:"
    echo >&2
    echo >&2 "  -x  Install Xcode rather than CLT"
    exit 2
}


xcode=0
while getopts xh opt; do
    case "$opt" in
        x)
            xcode=1
            ;;
        \?|h)
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

# Enable Firewall
sudo defaults write /Library/Preferences/com.apple.alf globalstate -bool true
sudo defaults write /Library/Preferences/com.apple.alf allowsignedenabled -bool false

# Enable Stealth Mode
sudo defaults write /Library/Preferences/com.apple.alf stealthenabled -bool true

# Disable Bonjour multicast advertisements:
sudo defaults write /Library/Preferences/com.apple.mDNSResponder.plist NoMulticastAdvertisements -bool YES

# Don't show hostname at the login screen
sudo defaults write /Library/Preferences/com.apple.loginwindow AdminHostInfo ""

# Crank up the max open files, etc
sudo sh -c "echo kern.sysv.shmall=65536 >>/etc/sysctl.conf"
sudo sh -c "echo kern.sysv.shmmax=16777216 >>/etc/sysctl.conf"
sudo sh -c "echo kern.maxfiles=10485760 >>/etc/sysctl.conf"
sudo sh -c "echo kern.maxfilesperproc=1048576 >>/etc/sysctl.conf"
sudo sh -c "sort -u /etc/sysctl.conf >/tmp/foo && mv /tmp/foo /etc/sysctl.conf"
sudo sysctl -w $(cat /etc/sysctl.conf)

# Sane permissions for /opt
sudo mkdir -p /opt
sudo chmod g+wXs /opt
sudo chgrp -R admin /opt
sudo find /opt -type d -exec chmod g+wXs "{}" \;
sudo find /opt -not -type d -exec chmod g+wX "{}" \;

# Add /usr/local/bin to the default PATH
sudo launchctl config user path /usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin

sudo dscl . create "$HOME" IsHidden 1
sudo fdesetup remove -user "$USER" || :

if ! xcode-select -p >/dev/null 2>&1; then
    if [ "$xcode" -eq 1 ]; then
        install-xcode
    else
        install-clt
    fi
fi
