#!/bin/sh
# Personal preferences and configuration. The settings in
# setup-admin/setup-user are what I'd consider reasonable defaults for anyone
# rather than my personal preferences.

# Autohide
defaults write com.apple.dock autohide -bool true
defaults write com.apple.dock tilesize 45

# Hide desktop icons completely
defaults write com.apple.finder CreateDesktop -bool false

# Disable Dashboard
defaults write com.apple.dashboard mcx-disabled -bool true
