#!/bin/bash

set -euo pipefail

scriptdir="$(cd "$(dirname "$0")" && pwd -P)"
PATH="${HOMEBREW_PREFIX:-$(brew --prefix 2>/dev/null || echo /usr/local)}/bin:$scriptdir:$PATH"

tmpdir="$PWD/$(mktemp -d "${0##*/}.XXXXXX")"
trap 'rm -rf "$tmpdir"' EXIT INT TERM

if [ ! -e "${HOMEBREW_PREFIX:-$HOME/.brew}/bin/brew" ]; then
    install-brew -s "${HOMEBREW_PREFIX:-$HOME/.brew}"
fi

# Apply spotlight privacy fixes
/usr/bin/python $scriptdir/fix-macosx.py

# Prevent auto-mounting of remote-filesystems by Finder
duti -vs com.apple.Safari afp
duti -vs com.apple.Safari ftp
duti -vs com.apple.Safari nfs
duti -vs com.apple.Safari smb

# Set your screen to lock as soon as the screensaver starts:
defaults write com.apple.screensaver askForPassword -int 1
defaults write com.apple.screensaver askForPasswordDelay -int 0

# Expose hidden files and Library folder in Finder:
defaults write com.apple.finder AppleShowAllFiles -bool true
chflags nohidden ~/Library

# Show all filename extensions (so that "Evil.jpg.app" cannot masquerade easily).
defaults write -g AppleShowAllExtensions -bool true

# Don't default to saving documents to iCloud:
defaults write -g NSDocumentSaveNewDocumentsToCloud -bool false

# Disable crash reporter (the dialog which appears after an application crashes and prompts to report the problem to Apple):
defaults write com.apple.CrashReporter DialogType none

# Enable Firewall
defaults write ~/Library/Preferences/com.apple.alf allowsignedenabled -bool false
defaults write ~/Library/Preferences/com.apple.alf globalstate -bool true

# Expand the save dialog by default in all applications
defaults write -g NSNavPanelExpandedStateForSaveMode -bool true

# Disable press-and-hold for keys in favor of key repeat
defaults write -g ApplePressAndHoldEnabled -bool false

# Use AirDrop over every interface
defaults write com.apple.NetworkBrowser BrowseAllInterfaces 1

# Stop full names from copying with email addresses in Mail.app
defaults write com.apple.mail AddressesIncludeNameOnPasteboard -bool false

# Always open everything in Finder's list view
defaults write com.apple.finder FXPreferredViewStyle Nlsv

# Enable quit menu item for Finder
defaults write com.apple.finder QuitMenuItem -bool true

# Enable text selection in quick look windows
defaults write com.apple.finder QLEnableTextSelection -bool true

# Remove autohide dock delay
defaults write com.apple.dock autohide-delay -float 0

# Speed up mission control animations
defaults write com.apple.dock expose-animation-duration -float 0.12

# Make hidden dock icons translucent
defaults write com.apple.dock showhidden -bool true

# Half-stars are great
defaults write com.apple.iTunes allow-half-stars -bool true

# Disable scroll gesture with modifier keys to zoom
#defaults write com.apple.universalaccess closeViewScrollWheelToggle -int 0
defaults write com.apple.AppleMultitouchTrackpad HIDScrollZoomModifierMask -int 0
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad HIDScrollZoomModifierMask -int 0

# Kill Skype's splash screen
defaults write com.skype.skype SKShowSplash NO

# Improve bluetooth audio quality over a2dp
defaults write com.apple.BluetoothAudioAgent "Apple Bitpool Min (editable)" 40

setup-apps
