#!/bin/sh

locate_app_by_id () {
    mdfind -onlyin /Applications "kMDItemContentType == 'com.apple.application-bundle' && kMDItemCFBundleIdentifier == '$*'"
}

app_installed () {
    test -n "$(locate_app_by_id "$*")"
}

duti_all () {
    if app_installed "$1"; then
        duti-all "$1"
    fi
}

ext_to_uti () {
    duti -e "$*" | sed -ne 's/^identifier: //p'
}


duti -vs com.googlecode.iterm2 public.unix-executable shell
duti -vs com.softwareambience.lilyview public.image viewer
duti -vs com.softwareambience.lilyview com.adobe.photoshop-image viewer
duti -vs org.mozilla.firefox public.html all
duti -vs org.mozilla.firefox public.xhtml all
duti -vs org.mozilla.firefox com.apple.web-internet-location all
duti -vs org.mozilla.firefox http
duti -vs org.mozilla.firefox https
duti -vs org.mozilla.firefox ftp
duti -vs org.videolan.vlc com.apple.quicktime-movie viewer
duti -vs org.videolan.vlc public.3gpp viewer
duti -vs org.videolan.vlc public.3gpp2 viewer
duti -vs org.videolan.vlc public.avi viewer
duti -vs org.videolan.vlc public.dv-movie viewer
duti -vs org.videolan.vlc public.flc-animation viewer
duti -vs org.videolan.vlc public.mpeg viewer
duti -vs org.videolan.vlc public.mpeg-4 viewer
if app_installed com.cocoatech.PathFinder; then
    duti -vs com.cocoatech.PathFinder public.folder viewer
fi
duti -vs com.amazon.SendToKindle .mobi viewer
duti -vs com.amazon.SendToKindle .azw viewer
# Opening packages in Suspicious Package ensures that you know what you're
# installing. There's a button in the app to run Installer.
duti -vs com.mothersruin.SuspiciousPackageApp com.apple.installer-package-archive viewer
duti -vs com.mothersruin.SuspiciousPackageApp x-apple-installer-package

# Switch these associations from Archive Utility to The Unarchiver
duti-all -n "/System/Library/CoreServices/Applications/Archive Utility.app" | \
    sed 's/com\.apple\.archiveutility/cx\.c3\.theunarchiver/; s/-s/-vs/;' | \
    tr '\n' '\0' | xargs -0 -n 1 -I"{}" sh -c "{}"
