#!/bin/sh

locate_app () {
    mdfind "kMDItemContentType == 'com.apple.application-bundle' && kMDItemDisplayName == '${*%.app}'cd"
}

locate_app_by_id () {
    mdfind -onlyin /Applications "kMDItemContentType == 'com.apple.application-bundle' && kMDItemCFBundleIdentifier == '$*'"
}

app_installed () {
    test -n "$(locate_app_by_id "$*")"
}

app_installed_directly () {
    for dir in /Applications ~/Applications /Applications/Utility ~/Applications/Utility; do
        if [ -d "$dir/$1.app" ]; then
            return 0
        fi
    done
    return 1
}

duti_all () {
    if app_installed_directly "$1"; then
        duti-all "$1"
    fi
}

ext_to_uti () {
    duti -e "$*" | sed -ne 's/^identifier: //p'
}


duti -vs com.googlecode.iterm2 public.unix-executable shell
if app_installed_directly "Path Finder"; then
    duti -vs com.cocoatech.PathFinder public.folder viewer
fi
if app_installed_directly "Send to Kindle"; then
    duti -vs com.amazon.SendToKindle .mobi viewer
    duti -vs com.amazon.SendToKindle .azw viewer
fi

# Switch these associations from Archive Utility to The Unarchiver
duti-all -n "/System/Library/CoreServices/Applications/Archive Utility.app" | \
    sed 's/com\.apple\.archiveutility/cx\.c3\.theunarchiver/; s/-s/-vs/;' | \
    tr '\n' '\0' | xargs -0 -n 1 -I"{}" sh -c "{}"

# Open these apps so they set up auto-start for themselves
while read -r bundle_id; do
    if app_installed "$bundle_id"; then
        open -gb "$bundle_id"
    fi
done <<END
ch.tripmode.TripMode
com.agilebits.onepassword4
com.backup42.desktop
com.bjango.istatmenus
com.expandrive.ExpanDrive3
com.flexibits.fantastical
com.getdropbox.dropbox
com.pilotmoon.popclip
com.runningwithcrayons.Alfred-3
com.surteesstudios.Bartender
org.herf.Flux
com.wulkano.kap
com.100hps.captin
com.crowdcafe.windowmagnet
com.briksoftware.unplugged
net.freemacsoft.AppCleaner
com.wiheads.paste
com.docker.docker
com.aptonic.Dropzone3
END

if test -n "$(locate_app "WiFi Signal")"; then
    open -ga "WiFi Signal" 2>/dev/null
fi

# Reload the Quick Look generators list
qlmanage -r
